CREATE TABLE USUARIOS(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USERNAME TEXT NOT NULL,
	PASSWORD TEXT,
	CARTAS TEXT,
	MONEDAS INTEGER
);

INSERT INTO USUARIOS(USERNAME, PASSWORD) VALUES ('benat', '123456');

SELECT * FROM USUARIOS;

